services:
  gpu-service:
    container_name: gpu-service
    image: atotti/gpu-service:latest
    working_dir: /app
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/nfs/
    command: sleep inf
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
