label_v = {
    "Tororo Ch. 猫麦とろろ",
    "アズマリム Azumalim",
    "SoraCh. ときのそらチャンネル",
    "Kuzuha Channel",
    "Pekora Ch. 兎田ぺこら",
    "宇推くりあ -★Clear Usui Rocket ch.★-",
    "かみと-KamitoChannel-",
    "花芽すみれ / Kaga Sumire",
    "花芽なずな / Nazuna Kaga",
    "ぽんぽこちゃんねる",
    "ピーナッツくん!オシャレになりたい!",
    "渋谷ハル",
    "赤見かるび / Karubi Akami",
    "天宮 こころ / Amamya Ch.",
    "樋口楓【にじさんじ所属",
    "文野環【にじさんじの野良猫】ふみのたまき",
    "兎咲ミミ / Tosaki Mimi",
    "小雀とと / Toto Kogara",
    "月ノ美兎",
    "如月れん -Ren kisaragi-",
    "おめがシスターズ [Ω Sisters]",
    "Nachoneko",
    "ヘアピンまみれ Hairpin Mamire",
    "天羽しろっぷ 【Amau Syrup】",
    "白雪レイドーReid Channelー",
    "Tomari Mari channel / 兎鞠まりちゃんねる",
    "astel ch.アステル",
    "柊ツルギ / Hiiragi Tsurugi",
    "星川サラ / Sara Hoshikawa",
    "夜絆ニウ / yozuna niu",
    "リゼ・ヘルエスタ -Lize Helesta-",
    "戌亥とこ -Inui Toko-",
    "Suisei Channel",
    "神楽めあ / KaguraMea",
    "Aruran Ch. アルランディス",
    "紫宮るな /shinomiya runa",
    "橘ひなの / Hinano Tachibana",
    "Akari ch.夢野あかり",
}
